language: node_js
node_js: 8
script: npm run test:coverage && npm run lint
cache:
  node: true
branches:
   only:
   - master
env: CXX=g++-4.8
addons:
   apt:
     sources: ubuntu-toolchain-r-test
     packages:
       - gcc-4.8
       - g++-4.8
